spring:
  profiles:
    active: 
      - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在位置
  type-aliases-package: com.ljpractice.springcloud.entities #所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #映射文件
spring:
  profiles: dev
  application:
    name: springcloud-config-gread-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://localhost:3306/lean?serverTimezone=GMT%2B8 #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 #数据库最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间



logging:
  level:
    com:
      ljpractice:
        springcloud:
          dao: debug   #打印SQL

eureka:
  client: #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #可以写多个 逗号分开
  instance:
    instance-id: springcloud-config-gread-client8001 #自定义服务器名称
    prefer-ip-address: true  #访问路径可以显示IP地址

info:
  app.name: ljpractice-springcloud
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
  
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在位置
  type-aliases-package: com.ljpractice.springcloud.entities #所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #映射文件
spring:
  profiles: test
  application:
    name: springcloud-config-gread-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://localhost:3306/lean?serverTimezone=GMT%2B8 #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 #数据库最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间



logging:
  level:
    com:
      ljpractice:
        springcloud:
          dao: debug   #打印SQL

eureka:
  client: #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #可以写多个 逗号分开
  instance:
    instance-id: springcloud-config-gread-client8001 #自定义服务器名称
    prefer-ip-address: true  #访问路径可以显示IP地址

info:
  app.name: ljpractice-springcloud
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}